### ISSUE TITLE
Which version of spaCy? Or which vocab model to use?

### ISSUE THREAD

**Issue by mathcass** [j2kao/fcc_nn_research#1]
Hi @j2kao, I started taking a look at your notebooks and learning more about how spaCy works. I got to cell #5 in [this notebook](https://github.com/j2kao/fcc_nn_research/blob/master/proc_17_108_analysis_jeffykao_EDA.ipynb) when I ran into a question for you about either the version of spaCy or the vocab model you're using. 

I installed `spacy==2.0.5` and the default model (`python -m spacy download en`) and when I generate word vectors, they have length 384 rather than the vectors of 300 that you were working with. 

Judging from this issue https://github.com/explosion/spaCy/issues/1657, some of the larger models use 300 length vectors while I think I'm working with one of the smaller ones. I was just curious to see which one you were using for this.

**Comment by j2kao** [comment]
Hey Cass, I used the default model, but with a different version.
```conda list``` gives me ```spacy 1.8.2 py36_0```.
```python -m spacy info``` gives me:
```
    spaCy version      1.8.2          
    Location           /home/jeff/anaconda3/lib/python3.6/site-packages/spacy
    Platform           Linux-4.13.0-26-generic-x86_64-with-debian-stretch-sid
    Python version     3.6.1          
    Installed models    en   
```
I think that difference must be giving you the different vector lengths. My guess is that any of the GloVe implementations will give you a similar result. As you imply, you probably don't have to downgrade spaCy if you use, e.g.: ```nlp = spacy.load('en_core_web_lg')```

**Comment by mathcass** [comment]
Thanks for the quick reply Jeff! That gives me some pointers if I want to replicate the results more closely. I'll probably download the larger model anyway.

**Comment by j2kao** [comment]
Happy to help! :smiley:
